# Generated by Django 5.0 on 2025-04-13 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='source',
        ),
    ]
